CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE tbl_disciplina (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Codigo" text NOT NULL,
    "Sigla" text NOT NULL,
    "CargaHoraria" integer NOT NULL,
    "TotalAulas" integer NOT NULL,
    CONSTRAINT "PK_tbl_disciplina" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250201171103_TblDisicplina', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE tbluserssaladias ADD disciplinaid integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250201172657_DisciplinaID', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE tbluser ADD "isAdmin" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250403160153_AdicionandoISaDMINpropriedade2', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE tblauth DROP COLUMN "accessToken";

ALTER TABLE tblauth DROP COLUMN userid;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250413130838_AlterandoTabelaAuth', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE tbldisciplina DROP COLUMN "TurmaId";

ALTER TABLE tblptd ADD "TurmaId" text;

ALTER TABLE tblauth ALTER COLUMN "tokenAvailableUntil" TYPE bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250413142250_AtualizandoEstrutura', '8.0.0');

COMMIT;

START TRANSACTION;

UPDATE tbluser SET username = '' WHERE username IS NULL;
ALTER TABLE tbluser ALTER COLUMN username SET NOT NULL;
ALTER TABLE tbluser ALTER COLUMN username SET DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250709231201_SupabaseMig01', '8.0.0');

COMMIT;

